/*
    RUN THIS IN THE SQL EDITOR IN SUPABASE
    --------------------------------------
*/

-- Create the students table
CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    grade VARCHAR(50) NOT NULL,
    gender VARCHAR(10) NOT NULL CHECK (gender IN ('Male', 'Female', 'Other')),
    status VARCHAR(10) DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    avatar VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert some dummy data
INSERT INTO students (student_id, name, email, grade, gender, status) VALUES 
('#STU-8821', 'Alex Rivers', 'alex.rivers@school.edu', 'Grade 11', 'Female', 'Active'),
('#STU-8822', 'Marcus Chen', 'm.chen@school.edu', 'Grade 10', 'Male', 'Active'),
('#STU-8823', 'Sarah Blake', 's.blake@school.edu', 'Grade 12', 'Female', 'Inactive'),
('#STU-8824', 'David Miller', 'd.miller@school.edu', 'Grade 9', 'Male', 'Active');
